# Generated by Django 3.2.22 on 2023-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_featured_image'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purchased_courses',
            field=models.ManyToManyField(blank=True, related_name='purchased_by', to='courses.Course'),
        ),
    ]
