# Generated by Django 3.2.22 on 2023-10-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='courses',
            field=models.ManyToManyField(to='courses.Courses'),
        ),
    ]
