# Generated by Django 3.2.22 on 2023-10-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coaches_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coaches',
            new_name='Coach',
        ),
        migrations.RenameModel(
            old_name='courses',
            new_name='Course',
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name_plural': 'Coaches'},
        ),
    ]
