# Generated by Django 3.2.22 on 2023-10-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20231016_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
