# Generated by Django 3.2.22 on 2023-10-18 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
