# Generated by Django 3.2.22 on 2023-11-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Testimonials'},
        ),
    ]
