# Generated by Django 3.2.22 on 2023-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_delete_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('biography', models.TextField(max_length=500)),
                ('accolades', models.TextField(max_length=500)),
                ('courses', models.ManyToManyField(to='courses.Course')),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
    ]
