# Generated by Django 3.2.22 on 2023-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_testimonials_options'),
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='coached_courses', to='courses.Course'),
        ),
    ]
