# Generated by Django 3.2.22 on 2023-11-07 11:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_alter_coach_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
